[2024-02-28T05:49:50.682+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-28T05:49:50.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-28T05:49:50.701+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2024-02-28T05:49:50.732+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists> on 2024-02-26 00:00:00+00:00
[2024-02-28T05:49:50.752+0000] {standard_task_runner.py:60} INFO - Started process 193 to run task
[2024-02-28T05:49:50.777+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'gcs_object_exists', 'scheduled__2024-02-26T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpdmcf9ig0']
[2024-02-28T05:49:50.792+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask gcs_object_exists
[2024-02-28T05:49:51.254+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-26T00:00:00+00:00 [running]> on host ae154badcbc6
[2024-02-28T05:49:51.498+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='gcs_object_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T00:00:00+00:00'
[2024-02-28T05:49:51.500+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, US-Stock-Market-Dataset.csv
[2024-02-28T05:49:51.517+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T05:49:51.525+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
[2024-02-28T05:49:52.077+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-02-28T05:49:52.098+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_snowflake_etl, task_id=gcs_object_exists, execution_date=20240226T000000, start_date=20240228T054950, end_date=20240228T054952
[2024-02-28T05:49:52.178+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-28T05:49:52.264+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
