[2024-02-27T22:04:30.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-27T22:01:15.680432+00:00 [queued]>
[2024-02-27T22:04:30.099+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-27T22:01:15.680432+00:00 [queued]>
[2024-02-27T22:04:30.100+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-02-27T22:04:30.127+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists> on 2024-02-27 22:01:15.680432+00:00
[2024-02-27T22:04:30.135+0000] {standard_task_runner.py:60} INFO - Started process 56 to run task
[2024-02-27T22:04:30.145+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'gcs_object_exists', 'manual__2024-02-27T22:01:15.680432+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpr7ea9mxl']
[2024-02-27T22:04:30.154+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask gcs_object_exists
[2024-02-27T22:04:30.255+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-27T22:01:15.680432+00:00 [running]> on host ae154badcbc6
[2024-02-27T22:04:30.394+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='gcs_object_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T22:01:15.680432+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T22:01:15.680432+00:00'
[2024-02-27T22:04:30.397+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, US Stock Market Dataset.csv
[2024-02-27T22:04:30.442+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 112, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 99, in poke
    hook = GCSHook(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 157, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 242, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2024-02-27T22:04:30.452+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_snowflake_etl, task_id=gcs_object_exists, execution_date=20240227T220115, start_date=20240227T220430, end_date=20240227T220430
[2024-02-27T22:04:30.483+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task gcs_object_exists (The conn_id `google_cloud_default` isn't defined; 56)
[2024-02-27T22:04:30.519+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T22:04:30.587+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
