[2024-02-28T17:05:21.785+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-28T17:05:18.498215+00:00 [queued]>
[2024-02-28T17:05:21.798+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-28T17:05:18.498215+00:00 [queued]>
[2024-02-28T17:05:21.800+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-28T17:05:21.818+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists> on 2024-02-28 17:05:18.498215+00:00
[2024-02-28T17:05:21.825+0000] {standard_task_runner.py:60} INFO - Started process 76 to run task
[2024-02-28T17:05:21.831+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'gcs_object_exists', 'manual__2024-02-28T17:05:18.498215+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmp1loza51n']
[2024-02-28T17:05:21.836+0000] {standard_task_runner.py:88} INFO - Job 269: Subtask gcs_object_exists
[2024-02-28T17:05:21.918+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-28T17:05:18.498215+00:00 [running]> on host 1753c686362f
[2024-02-28T17:05:22.018+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='gcs_object_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T17:05:18.498215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T17:05:18.498215+00:00'
[2024-02-28T17:05:22.020+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, Row-Data-US-Stock-Market-2020-to-2024.csv
[2024-02-28T17:05:22.032+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T17:05:22.037+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
[2024-02-28T17:05:22.560+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-02-28T17:05:22.573+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_snowflake_etl, task_id=gcs_object_exists, execution_date=20240228T170518, start_date=20240228T170521, end_date=20240228T170522
[2024-02-28T17:05:22.608+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-28T17:05:22.654+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
