[2024-02-28T12:10:26.906+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-28T12:10:26.922+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-28T12:10:26.923+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-02-28T12:10:26.951+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists> on 2024-02-27 00:00:00+00:00
[2024-02-28T12:10:26.960+0000] {standard_task_runner.py:60} INFO - Started process 112 to run task
[2024-02-28T12:10:26.965+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'gcs_object_exists', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmptahjn54j']
[2024-02-28T12:10:26.971+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask gcs_object_exists
[2024-02-28T12:10:27.054+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-27T00:00:00+00:00 [running]> on host b9a0bf70b495
[2024-02-28T12:10:27.248+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='gcs_object_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-02-28T12:10:27.256+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, US-Stock-Market-Dataset.csv
[2024-02-28T12:10:27.280+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T12:10:27.295+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
[2024-02-28T12:10:27.911+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-02-28T12:10:27.927+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_snowflake_etl, task_id=gcs_object_exists, execution_date=20240227T000000, start_date=20240228T121026, end_date=20240228T121027
[2024-02-28T12:10:27.983+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-28T12:10:28.050+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-28T16:06:15.142+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-28T16:06:15.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-02-28T16:06:15.160+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-02-28T16:06:15.188+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists> on 2024-02-27 00:00:00+00:00
[2024-02-28T16:06:15.196+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-02-28T16:06:15.202+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'gcs_object_exists', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpj2lpm71n']
[2024-02-28T16:06:15.207+0000] {standard_task_runner.py:88} INFO - Job 216: Subtask gcs_object_exists
[2024-02-28T16:06:15.311+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.gcs_object_exists scheduled__2024-02-27T00:00:00+00:00 [running]> on host 1753c686362f
[2024-02-28T16:06:15.460+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='gcs_object_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-02-28T16:06:15.462+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, /row_data/US-Stock-Market-2020-to-2024-Row-Data.csv
[2024-02-28T16:06:15.478+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T16:06:15.486+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
[2024-02-28T16:07:16.067+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, /row_data/US-Stock-Market-2020-to-2024-Row-Data.csv
[2024-02-28T16:07:16.083+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T16:07:16.086+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
[2024-02-28T16:08:16.649+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, /row_data/US-Stock-Market-2020-to-2024-Row-Data.csv
[2024-02-28T16:08:16.660+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T16:08:16.663+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
