[2024-02-29T19:37:35.354+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.create_snowflake_table scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-02-29T19:37:35.368+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.create_snowflake_table scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-02-29T19:37:35.369+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2024-02-29T19:37:35.387+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): create_snowflake_table> on 2024-02-28 00:00:00+00:00
[2024-02-29T19:37:35.393+0000] {standard_task_runner.py:60} INFO - Started process 55 to run task
[2024-02-29T19:37:35.398+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'create_snowflake_table', 'scheduled__2024-02-28T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpun52n0_d']
[2024-02-29T19:37:35.402+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask create_snowflake_table
[2024-02-29T19:37:35.491+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.create_snowflake_table scheduled__2024-02-28T00:00:00+00:00 [running]> on host 14357164fa05
[2024-02-29T19:37:35.592+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='create_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-28T00:00:00+00:00'
[2024-02-29T19:37:35.594+0000] {sql.py:276} INFO - Executing: 
                CREATE TABLE IF NOT EXISTS US_Stock_Market_2020_To_2024(
                    Date datetime,
                    Natural_Gas_Price float,       
                    "Natural_Gas_Vol." float,       
                    Crude_oil_Price float,       
                    "Crude_oil_Vol." float,       
                    Copper_Price float,       
                    "Copper_Vol." float,       
                    Bitcoin_Price float,       
                    "Bitcoin_Vol." float,       
                    Platinum_Price float,       
                    "Platinum_Vol." float,       
                    Ethereum_Price float,       
                    "Ethereum_Vol." float,       
                    "S&P_500_Price" float,     
                    "Nasdaq_100_Price" float,       
                    "Nasdaq_100_Vol." float,       
                    Apple_Price float,       
                    "Apple_Vol." float,      
                    Tesla_Price float,       
                    "Tesla_Vol." float,       
                    Microsoft_Price  float,       
                    "Microsoft_Vol." float,       
                    Silver_Price float,       
                    "Silver_Vol." float,      
                    Google_Price float,     
                    "Google_Vol." float,      
                    Nvidia_Price float,      
                    "Nvidia_Vol." float,     
                    Berkshire_Price float,    
                    "Berkshire_Vol." float,     
                    Netflix_Price float,       
                    "Netflix_Vol." float,      
                    Amazon_Price float,       
                    "Amazon_Vol." float,      
                    Meta_Price float,      
                    "Meta_Vol." float,      
                    Gold_Price float,      
                    "Gold_Vol." float,	
            );
        
[2024-02-29T19:37:35.611+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-29T19:37:35.630+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-29T19:37:35.631+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-02-29T19:37:35.633+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-29T19:37:36.162+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-29T19:37:36.259+0000] {cursor.py:1041} INFO - query execution done
[2024-02-29T19:37:36.260+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-29T19:37:36.261+0000] {sql.py:450} INFO - Running statement: CREATE TABLE IF NOT EXISTS US_Stock_Market_2020_To_2024(
                    Date datetime,
                    Natural_Gas_Price float,       
                    "Natural_Gas_Vol." float,       
                    Crude_oil_Price float,       
                    "Crude_oil_Vol." float,       
                    Copper_Price float,       
                    "Copper_Vol." float,       
                    Bitcoin_Price float,       
                    "Bitcoin_Vol." float,       
                    Platinum_Price float,       
                    "Platinum_Vol." float,       
                    Ethereum_Price float,       
                    "Ethereum_Vol." float,       
                    "S&P_500_Price" float,     
                    "Nasdaq_100_Price" float,       
                    "Nasdaq_100_Vol." float,       
                    Apple_Price float,       
                    "Apple_Vol." float,      
                    Tesla_Price float,       
                    "Tesla_Vol." float,       
                    Microsoft_Price  float,       
                    "Microsoft_Vol." float,       
                    Silver_Price float,       
                    "Silver_Vol." float,      
                    Google_Price float,     
                    "Google_Vol." float,      
                    Nvidia_Price float,      
                    "Nvidia_Vol." float,     
                    Berkshire_Price float,    
                    "Berkshire_Vol." float,     
                    Netflix_Price float,       
                    "Netflix_Vol." float,      
                    Amazon_Price float,       
                    "Amazon_Vol." float,      
                    Meta_Price float,      
                    "Meta_Vol." float,      
                    Gold_Price float,      
                    "Gold_Vol." float,	
            );, parameters: None
[2024-02-29T19:37:36.262+0000] {cursor.py:1028} INFO - query: [CREATE TABLE IF NOT EXISTS US_Stock_Market_2020_To_2024( Date datetime, Natural_...]
[2024-02-29T19:37:36.363+0000] {cursor.py:1041} INFO - query execution done
[2024-02-29T19:37:36.376+0000] {connection.py:718} INFO - closed
[2024-02-29T19:37:36.431+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-02-29T19:37:36.509+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1132, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01b2ae59-3201-024e-0000-000805ce90e9: SQL compilation error:
syntax error line 40 at position 12 unexpected ')'.
[2024-02-29T19:37:36.532+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_snowflake_etl, task_id=create_snowflake_table, execution_date=20240228T000000, start_date=20240229T193735, end_date=20240229T193736
[2024-02-29T19:37:36.559+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task create_snowflake_table (001003 (42000): 01b2ae59-3201-024e-0000-000805ce90e9: SQL compilation error:
syntax error line 40 at position 12 unexpected ')'.; 55)
[2024-02-29T19:37:36.576+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-29T19:37:36.612+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
